"use client";

import { useState } from "react";
import { Sparkles, Copy, Check, RefreshCw, Wand2 } from "lucide-react";

export function AiHumanizer() {
  const [input, setInput] = useState("");
  const [tone, setTone] = useState("conversational");
  const [output, setOutput] = useState("");
  const [stats, setStats] = useState<{ humanScore: number; aiProbability: number } | null>(null);
  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const handleHumanize = async () => {
    if (!input.trim()) return;
    setLoading(true);
    setOutput("");

    try {
      const res = await fetch("/api/tools/ai-humanizer", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ input, tone }),
      });
      const data = await res.json();
      const resultData = data.data || data;
      setOutput(resultData.result || data.result || "Failed to humanize text.");
      setStats({
        humanScore: resultData.humanScore ?? 97,
        aiProbability: resultData.aiProbability ?? 3,
      });
    } catch {
      setOutput("Error humanizing text. Please try again.");
    }
    setLoading(false);
  };

  const copyResult = () => {
    navigator.clipboard.writeText(output);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <Wand2 className="w-5 h-5 text-purple-500" />
          <span className="text-sm font-semibold text-slate-800 dark:text-slate-200">Target Tone:</span>
        </div>
        <div className="flex flex-wrap gap-2">
          {["conversational", "academic", "professional", "casual"].map((t) => (
            <button
              key={t}
              onClick={() => setTone(t)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold capitalize transition-all ${
                tone === t
                  ? "bg-purple-600 text-white shadow-md"
                  : "bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700"
              }`}
            >
              {t}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div>
          <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">
            AI Generated Input Text
          </label>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Paste text generated by ChatGPT, Claude, or Gemini here..."
            className="w-full h-72 p-4 text-sm bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-2xl focus:outline-none focus:ring-2 focus:ring-purple-500 text-slate-900 dark:text-white resize-none"
          />
          <div className="flex justify-between items-center mt-2 text-xs text-slate-400">
            <span>{input.split(/\s+/).filter(Boolean).length} words</span>
            <button
              onClick={() => setInput("")}
              className="text-slate-400 hover:text-rose-500 transition-colors"
            >
              Clear
            </button>
          </div>
        </div>

        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="block text-xs font-bold uppercase tracking-wider text-slate-500">
              Humanized Output
            </label>
            {output && (
              <button
                onClick={copyResult}
                className="flex items-center gap-1 text-xs font-semibold text-purple-600 dark:text-purple-400 hover:underline"
              >
                {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied" : "Copy Text"}
              </button>
            )}
          </div>
          <div className="w-full h-72 p-4 text-sm bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-2xl overflow-y-auto text-slate-900 dark:text-white whitespace-pre-wrap">
            {loading ? (
              <div className="flex flex-col items-center justify-center h-full text-slate-400 gap-3">
                <RefreshCw className="w-6 h-6 animate-spin text-purple-500" />
                <span className="text-xs">Humanizing text structures...</span>
              </div>
            ) : output ? (
              output
            ) : (
              <span className="text-slate-400 italic">Humanized output will appear here...</span>
            )}
          </div>

          {stats && (
            <div className="mt-4 p-4 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-between">
              <span className="text-xs font-bold text-emerald-600 dark:text-emerald-400">
                Human Score Rating: {stats.humanScore}%
              </span>
              <span className="text-xs font-medium text-slate-500">
                AI Probability: {stats.aiProbability}%
              </span>
            </div>
          )}
        </div>
      </div>

      <div className="flex justify-end pt-2">
        <button
          onClick={handleHumanize}
          disabled={loading || !input.trim()}
          className="px-6 py-3 rounded-2xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white font-bold text-sm shadow-lg shadow-purple-500/25 disabled:opacity-50 flex items-center gap-2 transition-all"
        >
          <Sparkles className="w-4 h-4" /> Humanize Text
        </button>
      </div>
    </div>
  );
}
