export interface CategoryDef {
  slug: string;
  name: string;
  description: string;
  icon: string;
  featured?: boolean;
  color: string;
}

export const CATEGORIES: CategoryDef[] = [
  {
    slug: "ai-tools",
    name: "AI Tools",
    description: "Next-gen AI utilities for text humanizing, detection, prompt optimization, and writing assistance.",
    icon: "Sparkles",
    featured: true,
    color: "from-purple-500 to-indigo-600",
  },
  {
    slug: "seo-tools",
    name: "SEO Tools",
    description: "Technical SEO utilities, schema generators, robot.txt tools, and meta tag analyzers.",
    icon: "Search",
    featured: true,
    color: "from-blue-500 to-cyan-600",
  },
  {
    slug: "text-tools",
    name: "Text Tools",
    description: "Text formatting, case manipulation, word counters, slug generators, and rewriters.",
    icon: "FileText",
    featured: true,
    color: "from-emerald-500 to-teal-600",
  },
  {
    slug: "writing-tools",
    name: "Writing Tools",
    description: "Grammar tools, paraphrasers, email writers, cover letters, and article generators.",
    icon: "PenTool",
    featured: true,
    color: "from-amber-500 to-orange-600",
  },
  {
    slug: "developer-tools",
    name: "Developer Tools",
    description: "Essential utilities for programmers, formatters, validators, and code generators.",
    icon: "Code",
    featured: true,
    color: "from-rose-500 to-pink-600",
  },
  {
    slug: "json-tools",
    name: "JSON Tools",
    description: "JSON formatting, validation, beautifiers, and minifiers.",
    icon: "Braces",
    featured: true,
    color: "from-yellow-500 to-amber-600",
  },
  {
    slug: "html-tools",
    name: "HTML Tools",
    description: "HTML formatters, clean code utilities, and markup generators.",
    icon: "Code2",
    featured: false,
    color: "from-orange-500 to-red-600",
  },
  {
    slug: "css-tools",
    name: "CSS Tools",
    description: "Gradient generators, CSS beautifiers, minifiers, and styling generators.",
    icon: "Palette",
    featured: false,
    color: "from-sky-500 to-blue-600",
  },
  {
    slug: "javascript-tools",
    name: "JavaScript Tools",
    description: "JS formatters, obfuscators, minifiers, and playground helpers.",
    icon: "Terminal",
    featured: false,
    color: "from-yellow-400 to-yellow-600",
  },
  {
    slug: "xml-tools",
    name: "XML Tools",
    description: "XML sitemaps, XML to JSON, and document formatters.",
    icon: "FileCode",
    featured: false,
    color: "from-indigo-400 to-indigo-600",
  },
  {
    slug: "programming-tools",
    name: "Programming Tools",
    description: "Regex testers, diff checkers, and algorithm helpers.",
    icon: "Cpu",
    featured: false,
    color: "from-cyan-500 to-blue-700",
  },
  {
    slug: "color-tools",
    name: "Color Tools",
    description: "Color pickers, palette generators, HEX/RGB converters, and gradient design tools.",
    icon: "Droplet",
    featured: true,
    color: "from-pink-500 to-purple-600",
  },
  {
    slug: "image-tools",
    name: "Image Tools",
    description: "Image resizers, canvas converters, QR code generators, and color tools.",
    icon: "Image",
    featured: true,
    color: "from-violet-500 to-fuchsia-600",
  },
  {
    slug: "pdf-tools",
    name: "PDF Tools",
    description: "Utilities for viewing, splitting, merging, and converting document formats.",
    icon: "FileUp",
    featured: true,
    color: "from-red-500 to-rose-600",
  },
  {
    slug: "finance-tools",
    name: "Finance Tools",
    description: "EMI calculators, interest calculators, and investment estimators.",
    icon: "DollarSign",
    featured: true,
    color: "from-green-500 to-emerald-700",
  },
  {
    slug: "math-tools",
    name: "Math Tools",
    description: "Scientific calculators, percentage calculators, and equation solvers.",
    icon: "Calculator",
    featured: true,
    color: "from-blue-600 to-indigo-800",
  },
  {
    slug: "health-calculators",
    name: "Health Calculators",
    description: "BMI calculators, calorie estimators, and age calculators.",
    icon: "HeartPulse",
    featured: true,
    color: "from-rose-400 to-red-600",
  },
  {
    slug: "unit-converters",
    name: "Unit Converters",
    description: "Convert length, mass, temperature, area, speed, and digital storage units.",
    icon: "ArrowLeftRight",
    featured: true,
    color: "from-teal-400 to-cyan-600",
  },
  {
    slug: "security-tools",
    name: "Security Tools",
    description: "Strong password generators, hash checkers, and security validators.",
    icon: "ShieldCheck",
    featured: true,
    color: "from-slate-700 to-zinc-900",
  },
  {
    slug: "hash-tools",
    name: "Hash Tools",
    description: "MD5, SHA-1, SHA-256, and SHA-512 cryptographic generators.",
    icon: "Lock",
    featured: false,
    color: "from-zinc-600 to-neutral-800",
  },
  {
    slug: "encoding-tools",
    name: "Encoding Tools",
    description: "Base64 encode/decode, URL encoding, HTML entity converters.",
    icon: "Binary",
    featured: false,
    color: "from-blue-700 to-indigo-900",
  },
  {
    slug: "generators",
    name: "Generators",
    description: "Lorem Ipsum, UUID generators, QR codes, and random text tools.",
    icon: "Wand2",
    featured: true,
    color: "from-amber-400 to-yellow-600",
  },
  {
    slug: "random-tools",
    name: "Random Tools",
    description: "Random numbers, random strings, coin flippers, and decision helpers.",
    icon: "Dices",
    featured: false,
    color: "from-indigo-500 to-purple-700",
  },
  {
    slug: "utility-tools",
    name: "Utility Tools",
    description: "Handy web utilities for daily tasks, conversions, and checks.",
    icon: "Wrench",
    featured: false,
    color: "from-gray-500 to-slate-700",
  },
  {
    slug: "social-media-tools",
    name: "Social Media Tools",
    description: "Hashtag generators, caption creators, and profile bio formatters.",
    icon: "Share2",
    featured: false,
    color: "from-sky-400 to-blue-600",
  },
  {
    slug: "productivity-tools",
    name: "Productivity Tools",
    description: "Reading time calculators, stopwatch tools, and work planners.",
    icon: "Zap",
    featured: false,
    color: "from-yellow-500 to-orange-600",
  },
  {
    slug: "student-tools",
    name: "Student Tools",
    description: "GPA calculators, citation helpers, and essay layout checkers.",
    icon: "GraduationCap",
    featured: false,
    color: "from-purple-600 to-indigo-800",
  },
  {
    slug: "business-tools",
    name: "Business Tools",
    description: "Invoice generators, ROI calculators, and business template tools.",
    icon: "Briefcase",
    featured: false,
    color: "from-blue-800 to-slate-900",
  },
  {
    slug: "marketing-tools",
    name: "Marketing Tools",
    description: "UTM builders, conversion estimators, and headline analyzers.",
    icon: "TrendingUp",
    featured: false,
    color: "from-emerald-600 to-teal-800",
  },
  {
    slug: "resume-tools",
    name: "Resume Tools",
    description: "Professional AI resume builders and cover letter generators.",
    icon: "FileBadge",
    featured: true,
    color: "from-cyan-600 to-blue-800",
  },
  {
    slug: "scientific-calculators",
    name: "Scientific Calculators",
    description: "Advanced trigonometry, logarithmic functions, and scientific math.",
    icon: "Atom",
    featured: false,
    color: "from-violet-700 to-purple-900",
  },
  {
    slug: "legal-templates",
    name: "Legal Templates",
    description: "Privacy policy generators, terms of service tools, and disclaimer builders.",
    icon: "Scale",
    featured: false,
    color: "from-amber-700 to-yellow-900",
  },
  {
    slug: "video-tools",
    name: "Video Tools",
    description: "AI video generation, cinematic motion clips, thumbnail downloaders, and video script writing.",
    icon: "Video",
    featured: true,
    color: "from-red-600 to-rose-700",
  },
  {
    slug: "audio-tools",
    name: "Audio Tools",
    description: "Speech to text, text to speech, and sound frequency utilities.",
    icon: "Headphones",
    featured: false,
    color: "from-indigo-600 to-purple-700",
  },
];
