import { constructMetadata } from "@/lib/seo";
import { siteConfig } from "@/config/site.config";
import { Breadcrumb } from "@/components/common/Breadcrumb";
import { FileCheck2, Scale, AlertCircle, ShieldAlert, Clock } from "lucide-react";

export const metadata = constructMetadata({
  title: `Terms of Service | ${siteConfig.name}`,
  description:
    "Review the terms and conditions for using Toolifia's free online AI tools, developer utilities, and web calculators.",
  canonicalUrl: `${siteConfig.url}/terms`,
});

export default function TermsOfServicePage() {
  const breadcrumbs = [{ name: "Terms of Service", url: "/terms" }];
  const lastUpdated = "July 26, 2026";

  return (
    <div className="min-h-screen py-8 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto space-y-10">
      <Breadcrumb items={breadcrumbs} />

      {/* Header Banner */}
      <div className="text-center space-y-4 max-w-3xl mx-auto">
        <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-brand-500/10 text-brand-600 dark:text-brand-400 text-xs font-bold uppercase tracking-wider border border-brand-500/20">
          <Scale className="w-4 h-4" /> Legal Terms & Conditions
        </div>
        <h1 className="text-3xl sm:text-5xl font-black text-slate-900 dark:text-white tracking-tight">
          Terms of Service
        </h1>
        <p className="text-base sm:text-lg text-slate-600 dark:text-slate-400 leading-relaxed">
          Please read these terms carefully before using {siteConfig.name}. By accessing or using our platform, you agree to be bound by these terms.
        </p>
        <div className="flex items-center justify-center gap-1.5 text-xs text-slate-400 font-medium">
          <Clock className="w-3.5 h-3.5" /> Effective Date: {lastUpdated}
        </div>
      </div>

      {/* Main Content */}
      <div className="p-8 sm:p-12 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xl space-y-8 text-slate-700 dark:text-slate-300 text-sm leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <FileCheck2 className="w-5 h-5 text-brand-500" /> 1. Acceptance of Terms
          </h2>
          <p>
            By accessing {siteConfig.name} (the "Service"), you agree to comply with and be bound by these Terms of Service. If you do not agree with any part of these terms, you must discontinue using the platform immediately.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">
            2. Permitted Use & Acceptable Conduct
          </h2>
          <p>
            {siteConfig.name} provides free web utilities, calculators, formatters, and AI text assistants for personal, educational, and commercial purposes. You agree not to:
          </p>
          <ul className="list-disc pl-5 space-y-2 text-slate-600 dark:text-slate-400">
            <li>Attempt to reverse engineer, automatedly scrape, or launch denial-of-service (DDoS) attacks against our API endpoints.</li>
            <li>Use the platform to generate illegal, abusive, defamatory, or harmful content.</li>
            <li>Bypass rate limits or security mechanisms governing API access.</li>
          </ul>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">
            3. Intellectual Property & User Output Ownership
          </h2>
          <p>
            <strong>Your Content:</strong> You retain 100% ownership rights over all text, code, images, and data you input into our utilities. Output generated by our tools (e.g. humanized text, formatted JSON, resized canvas images, XML sitemaps) is yours to use freely without royalty or attribution requirements.
          </p>
          <p>
            <strong>Platform IP:</strong> The {siteConfig.name} brand name, logo, custom tool code, UI design system, and technical architecture are the exclusive property of {siteConfig.name}.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <AlertCircle className="w-5 h-5 text-amber-500" /> 4. Disclaimer of Warranties
          </h2>
          <div className="p-4 rounded-xl bg-amber-500/10 border border-amber-500/20 text-amber-900 dark:text-amber-200 text-xs leading-relaxed font-medium">
            The Service is provided on an "AS IS" and "AS AVAILABLE" basis without warranties of any kind, whether express or implied. While we strive for 100% mathematical precision and reliable AI outputs, {siteConfig.name} does not warrant that tool outputs (e.g. financial EMI calculators, AI detection scores, code formatters) are completely error-free or legally binding.
          </div>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-rose-500" /> 5. Limitation of Liability
          </h2>
          <p>
            In no event shall {siteConfig.name}, its owners, developers, or affiliates be liable for any indirect, incidental, special, consequential, or punitive damages arising out of your access to, use of, or inability to use our free online tools.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">
            6. Changes to Terms
          </h2>
          <p>
            We reserve the right to update or modify these Terms of Service at any time. Continued use of the platform following published revisions constitutes acceptance of the updated terms.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-xl font-bold text-slate-900 dark:text-white">
            7. Contact Information
          </h2>
          <p>
            If you have questions regarding these Terms of Service, please use our{" "}
            <a href="/contact" className="text-brand-600 dark:text-brand-400 font-bold hover:underline">
              Contact page
            </a>{" "}
            to reach us.
          </p>
        </section>
      </div>
    </div>
  );
}
